# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 425dd7030b37e5714f9c0db739f2a6ff7f025f9a2c9bb1ef7aa6357fdf4e41a6721a13e5dceca8a31862877cd1e2fa9ba83dbce9b08f3e2d53bca932db761e84

test:
  secret_key_base: b40bbcbca061301e552852f816721ee6ede97a600000a270a27a026a964cec86178dd76232677079075e499ca898a8e8023396a55d63e04c67b34db24bcae73b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
